// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yugvnmtmiomtdkfuebfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Z3ZubXRtaW9tdGRrZnVlYmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTA1MzUsImV4cCI6MjA3MjgyNjUzNX0.l32yzrCl2KZRWfxRZUYFDwpZXKwoaGWoRlD4Umy7zkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});